### ISSUE TITLE
ALU Switch and ALU Control misalignment

### ISSUE THREAD

**Issue by rpolley** [rpolley/mips-processor#1]
The diagram in the book on page 376 seems to say to connect the 'ALU Control' output from the control unit should be connected to ALU's 'switch' input, however 'ALU Control' is 3 bits wide and 'switch' is 4 bits wide.

**Comment by hekemp** [comment]
I don't see a diagram on 376 so I'm assuming our books are different...

![image](https://cloud.githubusercontent.com/assets/14400687/25110802/632ddc0c-23ac-11e7-8569-2c8cdea7ccd7.png)

![image](https://cloud.githubusercontent.com/assets/14400687/25110833/9989b7c6-23ac-11e7-927a-8e8a07c3c3cc.png)

ALU is intended to be 3 bits wide though, as the table and diagram above support. I can see that his solution required 4 bits for the switch though... We may wish to inquire on this, but I'm thinking we need to do further conversion of the Alu Control output.

**Comment by hekemp** [comment]
Fixed in meeting
