### ISSUE TITLE
There is no output for any tests

### ISSUE THREAD

**Issue by ghost** [rpolley/mips-processor#2]
Run the test 'make p2sc' with this branch. Unless I'm missing something the registers never change value from 00000000 for any test you run.

**Comment by rpolley** [comment]
I think I fixed it, but are you sure your test is right? it checks the value at the start of the instruction too I think so keep that in mind

**Comment by ghost** [comment]
I havent committed any of the custom tests to github yet. It has the issue of no changes with the provided starter tests.

**Comment by ghost** [comment]
If you open CPU-starter_kit.circ, I believe it is called, and just tick through the program manually you will see that $s0-$s2 do not change although they should at some point.
